### ISSUE TITLE
500 error returned while calling Cloud Function by Cloud Run running "gcr.io/endpoints-release/endpoints-runtime-serverless:2.24" as base image

### ISSUE THREAD

**Issue by mejuhi** [GoogleCloudPlatform/esp-v2#550] opened 2021-06-28 08:29 UTC
**Configuration details:**
Architecture is configured to connect cloud run and cloud functions using Cloud Endpoint using the following [documentation](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-functions).

ESPv2 image is running on Cloud run. Base image used by cloud run is  `gcr.io/endpoints-release/endpoints-runtime-serverless:2.24` which gets build using the following [script](https://github.com/GoogleCloudPlatform/esp-v2/blob/40caa16ea9b4231ab9272bce2c9dfcec95dee3e5/docker/serverless/gcloud_build_image)

Cloud run is running with following configuration:

CPU allocated: 2
Memory allocated: 2048
Concurrency: 80
Request timeout: 800 seconds
Auto-scaling: Min instances: 5
Auto-scaling: Max instances: 1,000

and using following docker image config:

```
FROM gcr.io/endpoints-release/endpoints-runtime-serverless: 2.24.0
USER root
ENV ENDPOINTS_SERVICE_PATH /etc/endpoints/service.json
COPY service.json \${ENDPOINTS_SERVICE_PATH}
ENV ESPv2_ARGS ^++^--cors_preset=basic++--cors_allow_method="GET,PUT,POST"++--backend_retry_num=2
RUN chown -R envoy:envoy \${ENDPOINTS_SERVICE_PATH} && chmod -R 755 \${ENDPOINTS_SERVICE_PATH}
USER envoy
ENTRYPOINT ["/env_start_proxy.py"]
```

**Error Details:**

We have started to see increase in connection error between Cloud Run (ESP) and Cloud function (Business logic layer). Cloud run running ESP returns HTTP code 500,  but request does not reach cloud function since we are not able to find any logs for invocation on cloud function's logs.

While going through trace details, for some request we have found following error message _"The request was aborted because there was no available instance."_

Attaching screenshots for details:
![image](https://user-images.githubusercontent.com/45816852/123602338-4432eb80-d816-11eb-97a1-a52aa2a72f96.png)
![image](https://user-images.githubusercontent.com/45816852/123603473-89a3e880-d817-11eb-8291-d96a31ef932d.png)
![image](https://user-images.githubusercontent.com/45816852/123604423-75142000-d818-11eb-8388-2e83197958ac.png)

Is there any configuration which can be added to ESP config to mitigate these type of error, since frequency of this has  increased in last couple of weeks

**Comment by MrEfrem** [comment] 2021-06-28 13:14
I see the same errors on 2.28.

**Comment by shuoyang2016** [comment] 2021-06-28 18:07
> Is there any configuration which can be added to ESP config to mitigate these type of error, since frequency of this has increased in last couple of weeks

Hi mejuhi,
I am just trying to understand the timeline. Did you start to see this error when you upgraded to 2.24? Or when did you start to see this increasing and what were the changes around that timeframe?

**Comment by mejuhi** [comment] 2021-06-28 18:10
There was no change on Cloud endpoint, Cloud run running ESP-v2 image and Cloud function.
We have been using 2.24 since January 2020 and we have only started to see spike in these type of  errors since last two weeks

**Comment by qiwzhang** [comment] 2021-06-28 18:15
In the log details,  "response_code_details" field is "via_upstream".  This indicates that 500 is from some components between ESPv2 and your Cloud Function.  The error message "The request was aborted because there was no available instance." sound like Cloud function run out of resource, could not create a new instance to hand the requests.  Could you check your Cloud Function resource allocations, or your traffic load; number of requests per seconds to see if you can find any clues.

It seems that this is a cloud function load issue.  Maybe you can do a experiment, setup a load test, passing ESPv2,  direct the same load to your CF to see if it can handle the load.

**Comment by shuoyang2016** [comment] 2021-06-28 18:29
Agreed above. I searched "The request was aborted because there was no available instance." and it is indicating a cloud run error. Here are some sources about potential [cause](https://stackoverflow.com/questions/57007386/how-to-fix-cloudrun-error-the-request-was-aborted-because-there-was-no-availabl), [config change tuning](https://cloud.google.com/run/docs/about-instance-autoscaling) etc.

Since you didn't change ESPv2, the cause is likely coming from elsewhere. Your traffic load, cloudrun (cloudrun infra is also changing; it's possible to contact cloudrun as well) etc. It might be useful if you have metrics signals to look back when this error bumps and see what exactly had changed your stack at that timeframe.

I'll close this for this ESPv2 now. Please let us know if we can help anything else.

**Closed by shuoyang2016** 2021-06-28 18:29 UTC
