### ISSUE TITLE
Memory leak in v2.41.0?

### ISSUE THREAD

**Issue by davidgwps** [GoogleCloudPlatform/esp-v2#782] opened 2023-01-25 17:47 UTC
Hey, today we found that when we updated to v2.41.0 of ESPv2 there appears to be a memory leak 

![image](https://user-images.githubusercontent.com/88321759/214626270-98ec4af1-0897-4459-ade9-d1fb90e28976.png)

by contrast v2.38.0 does not have this problem and stays at a low memory usage

![image](https://user-images.githubusercontent.com/88321759/214628638-f572698f-02b3-4ea4-84dc-077b42a23bff.png)

see also this graph prior to the rollout, the big ramp whilst v2.41.0 was in use, and reverting the change restoring the memory back to normal levels

![image](https://user-images.githubusercontent.com/88321759/214630168-57ed8a66-a71f-4621-94ea-b2d67f9b9b90.png)

Our implementation:

```
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:2.41.0
          imagePullPolicy: Always
          args: [
            "--listener_port=8083",
            "--backend=127.0.0.1:8080",
            "--service={{ .Values.cloudEndpoints.hostName }}",
            "--rollout_strategy=managed",
          ]
```

**Comment by nareddyt** [comment] 2023-01-27 18:59
Thanks for reporting this. I have not been able to reproduce this yet with our test configurations. I wonder if there is a specific feature you are using that triggers this.

If possible, can you email your service configurations to nareddyt@google.com? You can download the file via:

```
gcloud endpoints configs describe "${CONFIG_ID}" \
  --project="${PROJECT}" \
  --service="${SERVICE}" \
  --format=json \
  > service.json
```

**Comment by nareddyt** [comment] 2023-02-13 16:50
Hi @davidgwps , I spent some time trying to reproduce it but haven't found any issues. This includes running ESPv2 with your configuration and also monitoring our long-running stress tests (https://testgrid.k8s.io/googleoss-esp-v2-periodic). Memory remained fairly constant, even under > 100 QPS load.

My recommendation for you to debug further: temporarily [enable the `--admin_port` flag](https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#debugging). Pass the flag `--admin_port=9000` to view that admin web UI on port `9000`. Once you do this:

- You can monitor the [memory usage](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--memory) endpoint to confirm if the memory leak is actually caused by ESPv2.
- If you find an instance with growing memory usage, use the [heap dump](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--heap_dump) endpoint to capture the heap state at the time. Feel free to use `pprof` to find which function the high memory usage is from. Or if you need help analyzing it, email the heap dump to me at nareddyt@google.com.

**Comment by mfiedorowicz** [comment] 2023-03-08 14:05
Hi @nareddyt, the issue reported here by @davidgwps seems to be caused by https://github.com/GoogleCloudPlatform/esp-v2/pull/759 enabling jwt caching by default and released with [v2.40.0](https://github.com/GoogleCloudPlatform/esp-v2/releases/tag/v2.40.0), significantly increasing memory consumption when dealing with a lot of individual JWTs being cached. 

Disabling it with `--jwt_cache_size=0` resolves the issue. 

Would be worth mentioning this flag on https://cloud.google.com/endpoints/docs/openapi/migrate-to-esp-v2 directly as it's quite significant change for anyone migrating from old ESP (it's documented on https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options though).

Also wondering if it's possibly related to https://github.com/envoyproxy/envoy/issues/14026 as showing similar symptoms.

**Comment by davidgwps** [comment] 2023-03-08 14:51
Thanks for the help @mfiedorowicz, it is 'fixed' by setting `--jwt_cache_size=0` for us too. I would personally considering reverting the the PR #759 too @nareddyt since the default behaviour of ESPv2 could now lead to this issue presenting itself without users realising.

**Comment by nareddyt** [comment] 2023-03-09 14:50
Thank you @mfiedorowicz and @davidgwps for finding this, makes sense. I was not able to reproduce it because I only tested with a small number of pre-set JWTs. Our test env is not setup to regenerate JWTs for each request.

> I would personally considering reverting the the PR #759 too @nareddyt since the default behaviour of ESPv2 could now lead to this issue presenting itself without users realising.

We enabled jwt cache by default because some customers were facing reliability problems with JWKS endpoints. If their endpoint temporarily serves errors or is unavailable, all requests flowing through ESPv2 would be buffered with long latency. Long latency is a harder problem to debug and causes much frustration. It can also lead to traffic backlog if the proper timeouts are not configured.

We'd like to keep this turned on by default, but perhaps the default cache size is too high. We choose the current size of 100k tokens based on the discussion here: https://github.com/GoogleCloudPlatform/esp-v2/pull/759#discussion_r1037270947

Perhaps our estimates were not accurate. @mfiedorowicz or @davidgwps , did either of you try a much smaller `--jwt_cache_size` instead of just setting it to 0?

> Also wondering if it's possibly related to https://github.com/envoyproxy/envoy/issues/14026 as showing similar symptoms.

I'm currently unclear if the problem is due to bad cache size estimate or actual memory leak. Let's try smaller sizes first to confirm.

> Would be worth mentioning this flag on https://cloud.google.com/endpoints/docs/openapi/migrate-to-esp-v2 directly

Ideally this flag is internal implementation detail that users don't need to worry about. But we can mention it if a lower value continues to cause problems.

**Comment by LCartwright** [comment] 2023-03-14 11:19
Thanks @nareddyt, A little more digging on the potential cause of the "memory leak" like behaviour has turned up this smoking gun in envoys [JWT Cache Implementation](https://github.com/envoyproxy/envoy/blob/27387070f8de03c94c7531feae7db9aa87f36740/source/extensions/filters/http/jwt_authn/jwt_cache.cc#L18) defaults. Suggesting a maximum JWT size of 4KiB, this is in contrast to the [#759 comment](https://github.com/GoogleCloudPlatform/esp-v2/issues/782#:~:text=the%20discussion%20here%3A-,%23759%20(comment),-Perhaps%20our%20estimates) which mentions a maximum of 100B. 

If this is indeed the real maximum, then the total memory increase for JWT caching would be more in the realms of 410MB with the default 100k cache value, not the 10MB stated in the comment. This is assuming ESPv2 does not do any maximum JWT size filtering itself.

**Closed** 2023-03-23 17:00 UTC
Labels: bug
