### ISSUE TITLE
ESPv2 not respecting the terminate signal

### ISSUE THREAD

**Issue by davidgwps** [GoogleCloudPlatform/esp-v2#743] opened 2022-10-12 17:11 UTC
Hey, 

How do I gracefully shutdown a ESPv2 container? It doesn't seem that SIGTERM is being listened to.

I have just migrated from using ESP to ESPv2, and running into a problem whilst doing a rolling upgrade of a pod where the terminating pod stays stuck in a terminating state until the graceful shutdown period elapses and kubernetes kills it a few minutes later.

I've run the pod with and without the ESPv2 container, and this only happens with ESPv2 enabled and running locally in minikube or in GKE.

```yaml
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:2
          imagePullPolicy: Always
          args: [
            "--listener_port=8083",
            "--backend=127.0.0.1:8080",
            {{- if eq .Values.k8s.minikube.enabled false }}
            "--service={{ .Values.cloudEndpoints.hostName }}",
            "--rollout_strategy=managed",
            {{- else }}
            "--service_json_path=/etc/espv2_config/service_config.json",
            "--non_gcp",
            "--enable_debug",
            {{- end }}
          ]
          ports:
            - containerPort: 8083
          {{- if .Values.k8s.minikube.enabled }}
          volumeMounts:
            - mountPath: /etc/espv2_config
              name: service-config-volume
          {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8083
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8083
```

The debug logs in the ESPv2 container keep on churning out constantly, also indicating it is still running

[scratch.txt](https://github.com/GoogleCloudPlatform/esp-v2/files/9767240/scratch.txt)

kubes pod events showing that the container is attempted to be killed

```
│   Normal   Created    27m                kubelet            Created container esp                                                                                                                                                                        │
│   Normal   Started    27m                kubelet            Started container esp 
│   Normal   Created    27m                kubelet            Created container my_container                                                                                                                                                                   │
│   Normal   Started    27m                kubelet            Started container my_container                                                                                                                                                                   │
│   Warning  Unhealthy  27m (x2 over 27m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503                                                                                                                               │
│   Normal   Killing    3s                 kubelet            Stopping container esp                                                                                                                                                                       │
│   Normal   Killing    3s                 kubelet            Stopping container my_container 
```

Any help appreciated,
David

**Comment by qiwzhang** [comment] 2022-10-17 16:30
It seems that envoy is not quiting after received SIGTERM.   Maybe related to  health checking of `8083/healthz` you setup.

I did not see you use the `--healthz` [flag](https://github.com/GoogleCloudPlatform/esp-v2/blob/master/docker/generic/start_proxy.py#L244).  But your GKE deployment uses it.

As a test,  maybe you can try to health check on your `8080` directly to see if Envoy quits.

**Comment by DawidJanczak** [comment] 2022-11-28 09:56
I think I just run into the same issue. I _am_ passing the `healthz` flag as the option, but despite that same thing happens as described here - the pod gets stuck in terminating state until it's killed. v1 works just fine.

**Comment by DawidJanczak** [comment] 2022-11-28 10:03
The additional oddity here is that the ingress still seems to be forwarding traffic to those terminating pods resulting in some 503s for our users. The endpoints change as soon as the new pods appear, but something is causing the traffic to stick to the old pods.

**Comment by nareddyt** [comment] 2022-11-29 16:07
Hi @qiwzhang , assigned this to you. I saw you already started researching it

**Comment by qiwzhang** [comment] 2022-11-29 16:33
Yes,  thanks

**Comment by qiwzhang** [comment] 2022-11-29 19:12
Here is the status update:

The key of the issue is to kill ESP pod by `kubectrl delete pod` before the `--grace-period`.  ESP pod can be killed after grace-period, but its default is 30s.  Users want it to be killed before that.

I tested ESPv2 pod,  it could not.  But I also tested with stock envoy image,  it can.

My first suspicious is our [start_proxy.py](https://github.com/GoogleCloudPlatform/esp-v2/blob/master/docker/generic/start_proxy.py#L1508) which is the parent process running both envoy and config_mgr.  It did not propagate any signals to its child processes.  

I used this [pr](https://github.com/GoogleCloudPlatform/esp-v2/pull/756) to study when SIGTERM is received. My tests showed that `kubectrl delete pod` only send `SIGTERM` signal to it after `--grace-period`.   

So I am puzzling now...   I don't know what signal "kubectrl" send to the top process when `delete pod` is issued.  and I don't know how stock envoy can be killed, but not ours.

**Comment by nareddyt** [comment] 2022-11-29 20:05
> and I don't know how stock envoy can be killed, but not ours.

https://github.com/envoyproxy/envoy/blob/3752119b94ae4a5ff337364f585f54305406dc7f/source/server/server.cc#L849-L873

Maybe `SIGINT` instead of `SIGTERM`?

**Comment by qiwzhang** [comment] 2022-11-29 20:07
Not, start_proxy.py did not receive `SIGINT`

**Comment by orionHong** [comment] 2022-12-01 05:15
I did some [readings](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace), and it seems when the pod starts terminating, the parent process should receive a SIGTERM. Then, if the process is terminated before the grace period (a SIGTERM handler is needed for this to happen), the pod is removed immediately. If the process is not terminated after the grace period, any running processes will receive SIGKILL.

> I used this https://github.com/GoogleCloudPlatform/esp-v2/pull/756 to study when SIGTERM is received. My tests showed that kubectrl delete pod only send SIGTERM signal to it after --grace-period.

So this does sound odd. Did we see SIGTERM signal handler being triggered after the grace period in #756, or was the process terminated immediately?

Theoretically, if SIGTERM is propagated to envoy and config manager, the process and the pod should exit before the grace period.

**Comment by qiwzhang** [comment] 2022-12-03 01:34
Maybe I tested it wrong.    It seems that this pr should work https://github.com/GoogleCloudPlatform/esp-v2/pull/756

**Closed** 2022-12-06 22:01 UTC
Labels: bug

**Comment by davidgwps** [comment] 2022-12-07 14:46
thanks for the fix, once it is released I will try it out!
