### ISSUE TITLE
Misleading error message when JWT is unauthorized

### ISSUE THREAD

**Issue by chrisfrank** [GoogleCloudPlatform/esp-v2#472] opened 2021-01-30 17:44 UTC
ESPv2 reports `jwt_authn_access_denied{Jwt_is_missing}` when it rejects requests that _do_ include a JWT, if the JWT is signed by a service account not authorized to call the API. Rejecting these requests is of course correct, but the error message was hard for me to debug. I was trying to figure out why the `Authorization: Bearer {JWT}` header wasn't being passed to ESPv2 at all, when in fact it was being passed, just with an unauthorized token. (I confirmed this by enabling the `--log_request_headers` startup option.)

An error message along the lines of `jwt_authn_access_denied{Jwt_is_unauthorized}` would, I think, be easier to debug.

**Comment by TAOXUY** [comment] 2021-01-31 03:17
Hi Chris, 

I suspect you defined:
- [x-goog-jwt-locations](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#x-google-jwt-locations) in your openapi config if you are using ESPv2 on http backend
- [Authentication.providers.jwt_locations](https://github.com/googleapis/googleapis/blob/1d641ec6515408e9919402a4be70ff361f65ebbf/google/api/auth.proto#L168) in your [yaml config](https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#authentication) if you are using ESPv2 on gRPC backend

Either of them should overwrite the default JWT location settings.

A quick check could be setting [--enable_debug](https://github.com/GoogleCloudPlatform/esp-v2/blob/3892b9e2413fc8e23050bd8bd230b7723677b00b/docker/generic/start_proxy.py#L577) for ESPv2 and checking the envoy config log in the application log of ESPv2. You should be able to find similar lines of [these](https://github.com/GoogleCloudPlatform/esp-v2/blob/3892b9e2413fc8e23050bd8bd230b7723677b00b/examples/auth/envoy_config.json#L176), which configs the location of extracting JWT.

**Comment by chrisfrank** [comment] 2021-02-01 14:25
Hi @TAOXUY,

I thought the same thing at first, but we're using the default JWT locations. That's why this error message was so perplexing! Here are more detailed steps to reproduce with an HTTP backend:

1. Using a service account that's permitted to call the API, sign a JWT.
2. Call the API with headers `Authorization: Bearer $(JWT)`.
3. Note that it works as expected.
4. Using a service account that is _not_ permitted to call the API, sign a JWT.
5. Call the API with headers `Authorization: Bearer $(UNAUTHORIZED_JWT)`.
6. Note the "Jwt_is_missing" error, even though the JWT is included in the request.

**Comment by qiwzhang** [comment] 2021-02-01 18:18
Hi Chris,

are you using `allow_without_credentail`  defined [here](https://github.com/googleapis/googleapis/blob/master/google/api/auth.proto#L69)

If so, it may explain it.   

When you use a new service account, "iss" field in JWT is different.  It doesn't match the one specified in service config.  It should report JwtUnkownIssuer error.  But since you have "allow_missing", ( `allow_without_credentail`  is translated into `allow_missing` in envoy config),  the error get translated into JwtMissing.
 Code is [here](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/jwt_authn/verifier.cc#L314).

It is a bug.  We will try to fix it.

Thanks

**Comment by TAOXUY** [comment] 2021-02-01 18:38
Hi Wayne, 

I think `allow_without_credential` is unrelated as it only turns the `JwtMissed` or `JwtUnkonwnIssuer` into `OK` [here](https://github.com/envoyproxy/envoy/blob/7d1a3a3e9a0d589e4284e452bd8cad5b28301e6b/source/extensions/filters/http/jwt_authn/verifier.cc#L319).  As Chris described, the request is rejected correctly by ESPv2 though the error message is misleading here, which we should fix.

Just made a reproduce test [here](https://github.com/GoogleCloudPlatform/esp-v2/pull/473/files). The fix should be the same [place](https://github.com/envoyproxy/envoy/blob/7d1a3a3e9a0d589e4284e452bd8cad5b28301e6b/source/extensions/filters/http/jwt_authn/verifier.cc#L314) but add some logic to use `JwtUnknownIssuer`

**Comment by qiwzhang** [comment] 2021-02-01 19:02
I see.  we are using `RequireAny` if there are more than 1 AuthRequirement.   `RequireAny` has this bug of not distinguishing between JwtMissing and JwtUnknownIssuer.

**Comment by qiwzhang** [comment] 2021-05-07 16:50
It has been fixed in upstream envoy

**Closed by qiwzhang** 2021-05-07 16:50 UTC
