### ISSUE TITLE
ESPv2 not forwarding original Authorization header when an x-google-backend is specified

### ISSUE THREAD

**Issue by fareeda0** [GoogleCloudPlatform/esp-v2#140] opened 2020-04-29 00:37 UTC
Noticed this behaviour recently.

I'm using ESPv2 as a gateway to connect multiple cloud run services. As such, I have multiple x-google-backends specified in my API spec.

As per the docs, if ESP needs to overwrite the original Authorization header, it will forward the original one in the X-Forwarded-Authorization header.

However, when I log the headers received by my cloud run services this forwarded header is missing.

Any ideas?

Thanks :)

**Comment by fareeda0** [comment] 2020-04-29 01:08
For some more info, these are the headers received by my cloud run service. The `Authorization` header is overwritten by ESPv2 and isn't the original header send by the client (in this case Postman)

```
{
    "host": "entities-qlke7n23aa-ew.a.run.app",
    "user-agent": "PostmanRuntime/7.24.1",
    "accept": "application/json",
    "cache-control": "no-cache",
    "postman-token": "da5a4c99-b566-44f0-a351-e4eb5d92abf7",
    "x-cloud-trace-context": "9e9591b2137b514bbca7680f58a1076d/15042261411070150171",
    "x-forwarded-for": "92.236.63.50,2600:1900:2000:91::",
    "x-forwarded-proto": "https",
    "forwarded": "for=\"92.236.63.50\";proto=https,for=\"2600:1900:2000:91::\";proto=https",
    "content-length": "0",
    "x-request-id": "08d3b30d-8480-9c42-80da-b48f7a8ba16b",
    "x-endpoint-api-userinfo": "<DECODED_JWT_PAYLOAD>",
    "authorization": "Bearer <ESPV2_JWT>",
    "accept-encoding": "gzip, deflate, br"
}
```

In my OpenAPI spec, here is the corresponding path:

```
get:
        tags:
          - organisation
        x-google-backend:
            address: <REDACTED>
            protocol: h2
            path_translation: APPEND_PATH_TO_ADDRESS
        security:
          - firebase: []
        summary: List all organisations
        operationId: listOrg
        responses:
          '200':
            description: A successful response
            schema:
              type: string
```

and here is the corresponding security definition (I'm using firebase)

```
firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/<REDACTED>"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "<REDACTED>"
```

**Comment by qiwzhang** [comment] 2020-04-29 01:38
Please make sure you are using ESPv2  2.7.0

https://github.com/GoogleCloudPlatform/esp-v2/releases/tag/v2.7.0

You can find out the esp version in Cloud Console in Endpoints log:

Cloud Console -> Endpoints -> your_service -> "view log" link at the right bottom

**Comment by fareeda0** [comment] 2020-04-29 01:48
From the logs, I am using 2.8.0 it seems. Is this an issue?


```
{
    ...
    request_latency_in_ms: 4422   
    request_size_in_bytes: 1038   
    response_size_in_bytes: 2298   
    service_agent: "ESPv2/2.8.0"   
    service_config_id: "2020-04-29r0"   
    timestamp: 1588119651.0365543   
    url: "/v2/entities/organisations"   
 }
 ```

Also as per your suggestion on Google Groups 

https://groups.google.com/forum/#!topic/google-cloud-endpoints/_PRIYw1Ccsc

I tried adding `disable_auth: true` to the `x-google-backend`

However, it did not work as I configured my cloud run service not to allow unauthenticated invocations.

**Comment by fareeda0** [comment] 2020-04-29 02:00
I re-deployed ESPv2 using v2.7.0 explicitly and it remains the same.

Original client auth header has changed, and no forwarded header from ESPv2.

**Comment by nareddyt** [comment] 2020-04-29 02:47
@qiwzhang meant to be sure you are using _at least_ 2.7.0, 2.8.0 should be fine. For reference, this feature was implemented in #90 and released in 2.7.0: https://github.com/GoogleCloudPlatform/esp-v2/releases/tag/v2.7.0

#90 also has integration tests that verify the `X-Forwarded-Authorization` header shows up on the backend, so this is odd. Let me do some digging.

First off, I confirmed that if you manually send `X-Forwarded-Authorization` in your request, then the backend will receive the header (before 2.7.0).

```
curl -H "X-Forwarded-Authorization: test" <ESPv2 URL>

"headers": {
    ...
    "user-agent": "curl/7.52.1",
    "accept": "*/*",
    "x-forwarded-authorization": "test",
    "x-forwarded-for": "47.14.119.5,2600:1900:2000:a4::9",
    "x-forwarded-proto": "https",
    "forwarded": "for=\"47.14.119.5\";proto=https,for=\"2600:1900:2000:a4::9\";proto=https",
    "content-length": "0",
    ...
}
```

This tells me neither GSLB or Cloud Run are filtering out the header, so that eliminates one possible source of error.

**Comment by nareddyt** [comment] 2020-04-29 03:00
And now I have deployed ESPv2 2.8.0 and confirmed the backend does NOT receive a `X-Forward-Authorization` header by default. This reproduces the problem you are having.

Once again, if you manually send the `X-Forwarded-Authorization` header in the request, then the backend receives it (unmodified). This is also surprising.

**Comment by fareeda0** [comment] 2020-04-29 03:06
> And now I have deployed ESPv2 2.8.0 and confirmed the backend does NOT receive a `X-Forward-Authorization` header by default. This reproduces the problem you are having.
> 
> Once again, if you manually send the `X-Forwarded-Authorization` header in the request, then the backend receives it (unmodified). This is also surprising.

Thanks for the update. Just confirmed the same via Postman (manually sending the header).

Is there anything further I can do on my end to help?

**Comment by nareddyt** [comment] 2020-04-29 03:08
Oh, I realized my mistake in my previous comment. I am not sending the `Auhorization` header.

ESPv2 will only add `X-Forwarded-Authorization` if you send an `Authorization` header, as described in the doc and your original comment.

I do see the `X-Forwarded-Authorization` header when I do this. Therefore, I am NOT able to reproduce your issue.

```
curl -H "Authorization: test" <ESPv2 URL>

"headers": {
   ...
    "user-agent": "curl/7.67.0",
    "accept": "*/*",
    "authorization": "Bearer <TOKEN>",
    "x-forwarded-authorization": "test",
    "x-forwarded-for": "2620:15c:2c4:203:6df0:7e67:8d49:162b,2600:1900:2000:a5:400::2",
    "x-forwarded-proto": "https",
    "forwarded": "for=\"2620:15c:2c4:203:6df0:7e67:8d49:162b\";proto=https,for=\"2600:1900:2000:a5:400::2\";proto=https",
    "content-length": "0",
   ...
}
```

@fareeda0, are you 100% sure you are sending the `Authorization` header?

**Comment by fareeda0** [comment] 2020-04-29 03:14
Oh that's strange, and yep I'm sending it 100%

Here is the curl from Postman just with the URL and TOKEN not shown.

```
curl --location --request GET '<URL>' \
--header 'Authorization: Bearer <TOKEN>'
```

**Comment by fareeda0** [comment] 2020-04-29 03:21
The original <TOKEN> that is sent is an id_token from firebase, and the decoded payload contains the user info as expected.

However the decoded token received by my cloud run service contains info for the default compute service account - since ESPv2 uses that service account to invoke the corresponding `x-google-backend`

So the Authorization header is definitely being overwritten. Could it be an issue in my OpenAPI spec perhaps?

**Comment by fareeda0** [comment] 2020-04-29 03:32
@nareddyt 

Okay so a further development. I removed the `firebase` security definition from the path and I am now able to see the `X-Forwarded-Authorization` header in my backend.

Now I'm wondering why the firebase security definition would affect this. I set up the security def exactly as per the docs.

**Comment by nareddyt** [comment] 2020-04-29 03:35
Thanks, I was just testing out that theory. This is a edge case we didn't think of and can be better documented.

You have configured ESPv2 to validate the Authorization token from firebase. This uses Envoy's JWT authn filter, which will actually remove the `Authorization` header once it's validated. Instead, it will set the decoded payload in the `X-Endpoint-API-UserInfo`. This is documented here: https://cloud.google.com/endpoints/docs/openapi/migrate-to-esp-v2#handle-jwt

> With ESPv2 Beta, the `X-Endpoint-API-UserInfo` header only contains the Base64 encoded payload of the original JWT without modification.

So essentially in the case where a user configures JWT authentication, we end up not preserving the original header in `X-Forwarded-For` (because the `Authorization` header is removed before we copy it in #90). @qiwzhang, are you aware of any way to workaround this?

@fareeda0 do you really need the entire original `Authorization` header in `X-Forwarded-Authorization`? Or can you just use the decoded payload in the `X-Endpoint-API-UserInfo` header?

**Comment by nareddyt** [comment] 2020-04-29 03:37
Especially if you just want to check the claims in the JWT, then `X-Endpoint-API-UserInfo` should have everything you need. I can't think of a use case where you would need the entire original `Authorization` header. But if it's needed, we can try to find a way to copy it to `X-Forwaded-Authorization` as well.

**Comment by fareeda0** [comment] 2020-04-29 03:44
Ah okay I see, that makes a lot of sense.

I do make use of the `X-Endpoint-API-UserInfo` header, but I need access to the original token to communicate with other back ends that use the `firebase` security definition.

For example, say I have service A, service B that sit behind ESP

A flow might be:

```
Client -> ESP Gateway -> Service A -> Service B -> Service A -> Client
```

With this approach I can communicate with Service B using the same endpoints that the client would - it saves me having to write endpoints / controllers for strict service to service communication.

**Comment by qiwzhang** [comment] 2020-04-29 04:23
Thanks @nareddyt  for your investigation.   You have found the problem.  Envoy jwt_authn Provider has "forward" flag,  if it is false,  the original "Authorization" header will be removed.

ESPv2 set it to false by default.   But this is different behavior than v1.   I think we can just set it to true by default to behave the same as ESPv1.

**Comment by fareeda0** [comment] 2020-04-29 12:19
@qiwzhang 

Would you mind pointing me in the right direction as to where I can add the `forward` flag myself?

Keen to test it out and see how it works.

Thanks

**Comment by qiwzhang** [comment] 2020-04-29 16:32
@fareeda0 This the [flag](https://github.com/envoyproxy/envoy/blob/master/api/envoy/extensions/filters/http/jwt_authn/v3/config.proto#L124)

But ESPv2 users could not set it directly.  It is auto generated by this [code](https://github.com/GoogleCloudPlatform/esp-v2/blob/master/src/go/configgenerator/listener_generator.go#L386)

**Comment by nareddyt** [comment] 2020-04-29 16:44
I'll make a PR to fix this today. We can give you a test image (not for use in production) afterwords if you would like to try it out.

**Comment by fareeda0** [comment] 2020-04-29 17:17
Thanks @nareddyt @qiwzhang that would be great!

**Comment by fareeda0** [comment] 2020-04-29 21:42
Hey @nareddyt just wanted to say thanks for sorting this out so quickly!

Just wondering how I can build the new image?

I checked out your branch with the applied fix, and submitted the `cloudbuild.yaml` to Cloud Build, but it failed shortly thereafter haha. 😅

**Comment by nareddyt** [comment] 2020-04-29 21:54
Glad to help. I don't remember how to build the image (we let our CI do that). But this is the one built for that PR: gcr.io/cloudesf-testing/apiproxy-serverless:8de243ce8354f0c0222a122eb8675170c73d9a95

You should be able to use it if you just redo [this step of the tutorial](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-run#configure_esp), but pass in the test image to the script.

```
./gcloud_build_image -s CLOUD_RUN_HOSTNAME \
    -c CONFIG_ID -p ESP_PROJECT_ID \
    -i gcr.io/cloudesf-testing/apiproxy-serverless:8de243ce8354f0c0222a122eb8675170c73d9a95
```

We'll make a release with this PR later, but you can use the step above if you don't want to wait for a release 👍

**Comment by fareeda0** [comment] 2020-04-29 22:05
That’s exactly what I needed, I’ve set up a CICD pipeline to automate the ESPv2 deployment - so I can just pass it the gcr.io url you just provided.

Thanks again 🙂

**Comment by fareeda0** [comment] 2020-04-29 22:20
@nareddyt Confirmed working! 🚀

**Comment by nareddyt** [comment] 2020-04-29 22:26
Awesome, glad to help!

**Closed** 2020-04-29 23:50 UTC
Labels: bug
